feat: auto renew bot & indexer
starknet-id/auto_renew_bot pull request #2
Opened 2023-05-09 21:43 UTC by irisdv

Close #1 

This PR implements 2 crates :
- Indexer: index domain to addr update, addr to domain update, domain transfer, starknetid update, toggled renewals and approval events.
- Bot : renew bot which runs every 24 hours, fetches domains with an expiry date < 30 days, checks auto-renew has been enabled and that renewer has a sufficient allowance. 

**Testing :** 
You can test the indexer and renewal bot on the devnet.

If not on macos you can use `docker-compose` configuration file in this repo. 
Otherwise, directly run devnet using flags `--seed 0` and `--timeout 5000` and apibara using this command `OTEL_SDK_DISABLED=true RUST_LOG=info cargo run --release -p apibara-starknet -- start --devnet --rpc http://localhost:5050/rpc --wait-for-rpc`

Testing scripts are available in this PR : https://github.com/starknet-id/auto_renew_contract/pull/2

2023-05-16 19:39 UTC, Th0rgal reviewed
A few things to change. Rule of thumb for unwrap:
- It's a value we provide in the config: you can keep it
- It's a value that comes from a friendly actor (e.g. apibara): try to manage it if possible, but it's not a big deal
- It could fail for a random reason (a connection stopped) or worse if someone does it intentionally: we must take care of it

2023-05-16 19:39 UTC, Th0rgal commented on indexer/src/processing.rs
> +    while let Some(message) = data_stream.try_next().await.unwrap() {
please try to remove this unwrap, the connection will probably get closed at some point, you can check https://github.com/starknet-id/analysor

2023-05-16 19:39 UTC, Th0rgal commented on indexer/src/processing.rs
> +                panic!("chain reorganization detected: {cursor:?}");
An alert would be nice when the program panic, we certainly need to look at it

2023-05-17 23:05 UTC, irisdv commented on bot/src/config.rs
> +    let config_path = if args.len() <= 1 {
yes it starts at 0, the first one is the program name. So if the len = 1 then there is only the program name, if it's greater then we take the second arg at the index = 1

2023-05-23 05:45 UTC, Th0rgal requested changes
Please improve the query, use lazy_static or a const when possible wth felts. I think the current version only supports goerli and devnet, would be nice to be able to use mainnet too.

2023-05-23 05:45 UTC, Th0rgal commented on bot/src/bot.rs
> +        SequencerGatewayProvider::starknet_alpha_goerli()
what about mainnet?

2023-05-23 05:45 UTC, Th0rgal commented on bot/src/bot.rs
> +    let futures: Vec<_> = all_domains
Doing one query per domain won't scale very well, let's try to do a single query with an aggregate and a project.

2023-05-23 05:45 UTC, Th0rgal commented on bot/src/bot.rs
> +                        calldata: vec![domain_encoded, FieldElement::from_dec_str("60").unwrap()],
this felt could be loaded from a const instead of parsed every time

2023-05-23 14:53 UTC, irisdv commented on bot/src/discord.rs
> +    let http = Http::new(&config.discord.token);
I used serenity to send messages : https://github.com/serenity-rs/serenity

2023-05-23 15:14 UTC, irisdv commented on bot/src/bot.rs
> +            selector: get_selector_from_name("batch_renew").unwrap(),
actually I could use the `selector!` macro no ?

2023-05-24 06:31 UTC, Th0rgal commented on bot/src/bot.rs
> +            selector: get_selector_from_name("batch_renew").unwrap(),
Yes I didn't know it was ran at compile time, it's much better :)

2023-05-24 06:37 UTC, Th0rgal commented on bot/src/discord.rs
> +    let http = Http::new(&config.discord.token);
Okay I checked and it's just a wrapper for reqwest::RequestBuilder so no need to cache it :)

2023-05-24 06:37 UTC, Th0rgal commented
great work, lgtm

2023-05-25 06:28 UTC, merged